export const ROLES = {
  MASTER: 'MASTER',
  PROFESSOR: 'PROFESSOR',
  STAFF: 'STAFF',
  VIEWER: 'VIEWER'
};

export const MENU_PERMISSIONS = {
  dashboard: [ROLES.MASTER, ROLES.PROFESSOR, ROLES.STAFF, ROLES.VIEWER],
  projects: [ROLES.MASTER, ROLES.PROFESSOR, ROLES.STAFF],
  performance: [ROLES.MASTER, ROLES.PROFESSOR, ROLES.STAFF],
  budgets: [ROLES.MASTER, ROLES.PROFESSOR],
  reports: [ROLES.MASTER, ROLES.PROFESSOR, ROLES.STAFF],
  users: [ROLES.MASTER],
  settings: [ROLES.MASTER]
};

export const REPORT_STATUS = {
  DRAFT: 'DRAFT',
  REVIEW: 'REVIEW',
  COMPLETED: 'COMPLETED'
};

export const PROGRAM_STATUS = {
  PLANNED: 'PLANNED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED'
};
